In [ ]:
#Goal Difference

import pandas as pd
import numpy as np

matches = pd.read_csv("../Data/cleaned/WorldCupMatches_C.csv")


#matches.head()

matches['GoalDifference'] = abs(
    matches['HomeTeamGoals'] - 
    matches['AwayTeamGoals'])

matches[['HomeTeamName','HomeTeamGoals','AwayTeamName','AwayTeamGoals', 'GoalDifference']].head()

    HomeTeamName  HomeTeamGoals AwayTeamName  AwayTeamGoals  GoalDifference
0         France              4       Mexico              1               3
1  United States              3      Belgium              0               3
2     Yugoslavia              2       Brazil              1               1
3        Romania              3         Peru              1               2
4      Argentina              1       France              0               1

In [10]:
matches['Winner'] = np.where(matches['HomeTeamGoals']> matches['AwayTeamGoals'],
                             matches['HomeTeamName'], 
                             np.where(
                                 matches['AwayTeamGoals']> matches['HomeTeamGoals'],
                                 matches['AwayTeamName'], 
                                 'Draw'))

matches[['HomeTeamName','HomeTeamGoals','AwayTeamName','AwayTeamGoals', 'Winner']].head()

    HomeTeamName  HomeTeamGoals AwayTeamName  AwayTeamGoals         Winner
0         France              4       Mexico              1         France
1  United States              3      Belgium              0  United States
2     Yugoslavia              2       Brazil              1     Yugoslavia
3        Romania              3         Peru              1        Romania
4      Argentina              1       France              0      Argentina

In [13]:
matches['ResultCategory'] = np.where(matches['GoalDifference'] >= 3,
	'Dominant Victory',
    np.where(matches['GoalDifference'] == 0,
	'Close Match',
	'Draw'
))

matches[['HomeTeamName','HomeTeamGoals','AwayTeamName','AwayTeamGoals', 'Winner', 'ResultCategory']].head()

,HomeTeamName,HomeTeamGoals,AwayTeamName,AwayTeamGoals,Winner,ResultCategory
0,France,4,Mexico,1,France,Dominant Victory
1,United States,3,Belgium,0,United States,Dominant Victory
2,Yugoslavia,2,Brazil,1,Yugoslavia,Draw
3,Romania,3,Peru,1,Romania,Draw
4,Argentina,1,France,0,Argentina,Draw

In [14]:
matches['HighScoring'] = np.where(matches['GoalDifference'] >= 5, 'Yes', 'No')

matches['HighScoring'].value_counts()

HighScoring
No     816
Yes     36
Name: count, dtype: int64

In [15]:
KnockOutKeywords = [
    'Final',
    'Semi-finals',
    'Quarter-finals',
    'Round of 16'
]

matches['KnockoutMatch'] = matches['Stage'].apply(lambda x: 'Yes' if any(k in str(x) for k in KnockOutKeywords) else 'No')

matches['KnockoutMatch'].value_counts()

KnockoutMatch
No     658
Yes    194
Name: count, dtype: int64

In [16]:
matches.to_csv(
    "../Data/cleaned/WorldCupMatches_featured.csv",
    index=False
)

In [ ]:
matches.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'HomeTeamName',
       'HomeTeamGoals', 'AwayTeamGoals', 'AwayTeamName', 'Winconditions',
       'Attendance', 'HalftimeHomeGoals', 'HalftimeAwayGoals', 'Referee',
       'Assistant1', 'Assistant2', 'RoundID', 'MatchID', 'HomeTeamInitials',
       'AwayTeamInitials', 'MatchDate', 'MatchTime', 'GoalDifference',
       'Winner', 'ResultCategory', 'HighScoring', 'KnockoutMatch'],
      dtype='str')